/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facebook;

import facebook4j.Comment;
import facebook4j.FacebookException;
import facebook4j.FacebookFactory;
import facebook4j.Like;
import facebook4j.PagableList;
import facebook4j.Post;
import facebook4j.Reading;
import facebook4j.ResponseList;
import facebook4j.User;
import facebook4j.auth.AccessToken;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Salvador RG
 */
public class PublicacionesFacebook extends javax.swing.JFrame {

    /**
     * Creates new form PublicacionesFacebook
     */
    facebook4j.Facebook facebook;
    private String appId;
    private String appSecret;
    private String accessToken;
    String[] datosTabla;
    LinkedList<String> idUSuarios;
    DefaultTableModel table;
    ResponseList<Post> feeds;
    PagableList<Comment> comments;

    public PublicacionesFacebook(String appId, String appSecret, String accesToken) {
        initComponents();
        this.appId = appId;
        this.appSecret = appSecret;
        this.accessToken = accesToken;
        DefaultTableModel table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }//end of isCellEditable, se sobrescribio el metodo isCellEditable para que los datos
            //mostrados en la tabla no se puedan editar
        };
        jTextNameUser.setEditable(false);
        jTextEmail.setEditable(false);
        jTextGender.setEditable(false);
        jTextDate.setEditable(false);
        jTextFieldLikesNumber.setEditable(false);
        facebook = new FacebookFactory().getInstance();
        idUSuarios = new LinkedList<>();
        datosTabla = new String[4];
        jTablePost.getTableHeader().setReorderingAllowed(false);
        table = new DefaultTableModel();
        jTextAreaComments.setLineWrap(true);
        jTextAreaPost.setLineWrap(true);
        jTextAreaComments.setEditable(false);
        jTextAreaPost.setEditable(false);

    }

    public PublicacionesFacebook() {
        initComponents();
        appId = "138667509800894";
        appSecret = "67115c2621e24f3c4d57135448d42e8d";
        accessToken = "CAACEdEose0cBAFQQfep4eRpzGhKd64E984TZCnpsGtKMaNQEwBg8CtAI6GxqNqvYnzu8EJyuoEIsV8vmpyj2eqRG0RHaZCZCa6p1w2p2K6bkWrLzZBIZAnluCzNvDoFZAZAfrqzuiZCgF6eGcuiUSRwRGKDz4gd4CinC6ulGLrmk6YbbQtu4IfxRZAaL1qIGfiE2xDUcZBTOIaXAZDZD";
        DefaultTableModel table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }//end of isCellEditable, se sobrescribio el metodo isCellEditable para que los datos
            //mostrados en la tabla no se puedan editar
        };
        jTextNameUser.setEditable(false);
        jTextEmail.setEditable(false);
        jTextGender.setEditable(false);
        jTextDate.setEditable(false);
        jTextFieldLikesNumber.setEditable(false);
        facebook = new FacebookFactory().getInstance();
        idUSuarios = new LinkedList<>();
        
        datosTabla = new String[4];
        jTablePost.getTableHeader().setReorderingAllowed(false);
        table = new DefaultTableModel();
        jTextAreaComments.setLineWrap(true);
        jTextAreaPost.setLineWrap(true);
        jTextAreaComments.setEditable(false);
        jTextAreaPost.setEditable(false);
    }
//    public LinkedList<Post> obtenerMuroPublico(String idUsuario, int numeroDePost) throws FacebookException {
//        ResponseList<Post> feeds = facebook.getFeed(idUsuario, new Reading().limit(numeroDePost));
//        LinkedList postPublicos = new LinkedList();
//        for (int i = 0; i < feeds.size(); i++) {
//            // Get post.
//            if (feeds.get(i).getMessage() == null) {
//
//            } else {
//                postPublicos.add(feeds.get(i));
//            }
//        }//end of for
//        return postPublicos;
//    }//end of obtenerMuroPublico

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePost = new javax.swing.JTable();
        jButtonVerPost = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboUsers = new javax.swing.JComboBox();
        jComboPostNumber = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNameUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextGender = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaPost = new javax.swing.JTextArea();
        jTextFieldLikesNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaComments = new javax.swing.JTextArea();
        jLabelImage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldQuienPublica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Publicaciones"));

        jTablePost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePost);

        jButtonVerPost.setText("Ver post");
        jButtonVerPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPostActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));

        jComboUsers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elija un usuario" }));

        jComboPostNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Numero de post", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jComboPostNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboPostNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Inforrmacion perfil"));

        jLabel1.setText("Nombre:");

        jTextNameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameUserActionPerformed(evt);
            }
        });

        jLabel4.setText("e-mail:");

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha de nacimiento:");

        jLabel3.setText("Sexo:");

        jTextGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNameUser))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextEmail))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDate))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextGender, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 144, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonVerPost, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerPost, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));

        jTextAreaPost.setColumns(20);
        jTextAreaPost.setRows(5);
        jScrollPane3.setViewportView(jTextAreaPost);

        jLabel6.setText("Likes.");

        jTextAreaComments.setColumns(20);
        jTextAreaComments.setRows(5);
        jScrollPane4.setViewportView(jTextAreaComments);

        jLabelImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setText("Publica:");

        jLabel5.setText("Fecha:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldLikesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuienPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFecha))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLikesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldQuienPublica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        facebook.setOAuthAppId(appId, appSecret);
        facebook.setOAuthPermissions("ads_management, ads_read, read_friendlists, create_event, create_note, email, export_stream, read_stream, user_friends, friends_about_me, friends_actions.books, friends_actions.music, friends_actions.news, friends_actions.video, friends_activities, friends_birthday, friends_education_history, friends_events, friends_games_activity, friends_groups, friends_hometown, friends_interests, friends_likes, friends_location, friends_notes, friends_online_presence, friends_photo_video_tags, friends_photos, friends_questions, friends_relationship_details, friends_relationships, friends_religion_politics, friends_status, friends_subscriptions, friends_videos, friends_website, friends_work_history, manage_friendlists, manage_notifications, manage_pages, photo_upload, publish_actions, publish_stream, read_friendlists, read_insights, read_mailbox, read_page_mailboxes, read_requests, read_stream, rsvp_event, share_item, sms, status_update, user_about_me, user_actions.books, user_actions.music, user_actions.news, user_actions.video, user_activities, user_birthday, user_education_history, user_events, user_friends, user_games_activity, user_groups, user_hometown, user_interests, user_likes, user_location, user_notes, user_online_presence, user_photo_video_tags, user_photos, user_questions, user_relationship_details, user_relationships, user_religion_politics, user_status, user_subscriptions, user_videos, user_website, user_work_history, user_posts, video_upload, xmpp_login");
        facebook.setOAuthAccessToken(new AccessToken(accessToken, null));
        try {
            //ciclo for que llevara el conteo de amigos
            for (int i = 0; i < facebook.getFriends().size(); i++) {
                User usuarioLista = facebook.getFriends().get(i);// Variable usuarioLista de tipo User que que guarda los detalles del amigo
                //en la posicion del ciclo for.
                //personalInformation de tipo User que obtiene el id del usuarioLista con el ciclo for.
                User personalInformationUser = facebook.getUser(usuarioLista.getId(), new Reading().fields());
                jComboUsers.addItem(usuarioLista.getName());//se agrega al jComboUsers el amigo que lleva el ciclo for extrayendo el nombre
                idUSuarios.add(personalInformationUser.getId());// idUsuarios es de tipo LinkedList<String> que guarda el id de cada amigo
            }//end of for recorre lista de amigos
            jComboUsers.addItem(facebook.getMe().getName());//se añade jComboUsers mi nombre de usuario
        } catch (Exception e) {
        }//end of try
    }                                 

     public void mostrarImagen (JLabel label, String url) throws MalformedURLException, IOException{
        ImageIcon imagen;
        URL linkURL = new URL(url);
        BufferedImage buffer = ImageIO.read(linkURL);
        imagen = new ImageIcon(buffer);
        label.setIcon(imagen);
    }//end of mostarImagen
     
    public void mostrarPost() throws MalformedURLException, IOException {
        //ciclo for que lleva el conteo de los post de la variable feeds
        for (int i = 0; i < feeds.size(); i++) {
            if (jTablePost.getSelectedRow() == i) {//condicion if que se cumple si la fila es igual al conteo de i en el ciclo
                Post postParaMostrar = feeds.get(i);
                jTextFieldFecha.setEditable(false);
                jTextFieldQuienPublica.setEditable(false);
                jTextFieldFecha.setText(postParaMostrar.getCreatedTime().toLocaleString().substring(0, 10));
                jTextFieldQuienPublica.setText(postParaMostrar.getFrom().getName());
                jTextAreaPost.setText(postParaMostrar.getMessage());
                PagableList<Like> likes = postParaMostrar.getLikes();
                jTextFieldLikesNumber.setText(String.valueOf(likes.size()));
                comments = feeds.get(i).getComments();
                for (int j = 0; j < comments.size(); j++) {
                    System.out.println("jjhbjhb: " + comments);
                    jTextAreaComments.setText("\n" + jTextAreaComments.getText() + "\n" + comments.get(j).getFrom().getName() + ": " + comments.get(j).getMessage() + "  ✌: " + comments.get(j).getLikeCount());
                }
                //guardar imagen y mostrarla en el jLabelImage
                ImageIcon image;
                if (feeds.get(i).getPicture() != null) {
                    mostrarImagen(jLabelImage, feeds.get(i).getPicture().toString());
                } else {
                    jLabelImage.getGraphics().clearRect(1, 1, jLabelImage.getWidth(), jLabelImage.getHeight());
                    jLabelImage.setEnabled(false);
                    jLabelImage.setText("Imagen no disponible");
                }

            }
        }
    }//end of mostrarPost

    public void buscarPostFromUser(int indexUser, int postUser) throws FacebookException {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("No. Post");
        table.addColumn("Fecha");
        table.addColumn("Post");
        table.addColumn("Quien publica");
        if (indexUser == jComboUsers.getItemCount()-1) {
            feeds = facebook.getFeed(facebook.getMe().getId(), new Reading().limit(postUser));
            //System.out.println("hola chava");
        } else {
            feeds = facebook.getFeed(idUSuarios.get(indexUser), new Reading().limit(postUser));
            //System.out.println("hola quien seas");
        }
        for (int i = 0; i < feeds.size(); i++) {
            // Get (string) message.
            datosTabla[0] = String.valueOf(i + 1);
            datosTabla[1] = feeds.get(i).getCreatedTime().toLocaleString();
            datosTabla[2] = feeds.get(i).getMessage();
            datosTabla[3] = feeds.get(i).getFrom().getName();
            table.addRow(datosTabla);
            jTablePost.setModel(table);
        }
    }//end of buscarPostFromUser

    public void informacionPersonalUsuario(int indexUser) throws FacebookException {
        if (indexUser == jComboUsers.getItemCount()-1) {
            User misDatos = facebook.getMe();
            jTextNameUser.setText(misDatos.getName());
            jTextEmail.setText(misDatos.getEmail());
            jTextDate.setText(misDatos.getBirthday());
            jTextGender.setText(misDatos.getGender());
            System.out.println("link: " + misDatos.getPicture().toString());
        } else {
            User datosPerfilUsuario = facebook.getUser(idUSuarios.get(indexUser));
            jTextNameUser.setText(datosPerfilUsuario.getName());
            if (datosPerfilUsuario.getEmail() == null || datosPerfilUsuario.getBirthday() == null) {
                jTextEmail.setText("Datos no diponibles");
                jTextDate.setText("Datos no diponibles");
            } else {
                jTextEmail.setText(datosPerfilUsuario.getEmail());
                jTextDate.setText(datosPerfilUsuario.getBirthday());
            }
            jTextGender.setText(datosPerfilUsuario.getGender());
            jTextNameUser.setText(datosPerfilUsuario.getName());
        }
    }//end of informacionPersonalUsuario

    public void deleteDatosUserAndPost() {
        jLabelImage.getGraphics().clearRect(1, 1, jLabelImage.getWidth(), jLabelImage.getHeight());
        jTextAreaComments.setText("");
        jTextAreaPost.setText("");
        jTextFieldLikesNumber.setText("");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        deleteDatosUserAndPost();
        if (jComboUsers.getSelectedIndex() != 0) {
            int miIndiceUsuario = jComboUsers.getItemCount() -1;
            if (jComboPostNumber.getSelectedIndex() != 0) {
                if (jComboUsers.getSelectedIndex() == miIndiceUsuario) {
                    try {
                        informacionPersonalUsuario(miIndiceUsuario);
                        buscarPostFromUser(miIndiceUsuario, Integer.parseInt(jComboPostNumber.getSelectedItem().toString()));
                    } catch (FacebookException ex) {
                        Logger.getLogger(PublicacionesFacebook.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    try {
                        informacionPersonalUsuario(jComboUsers.getSelectedIndex() - 1);
                        buscarPostFromUser(jComboUsers.getSelectedIndex() - 1, Integer.parseInt(jComboPostNumber.getSelectedItem().toString()));
                    } catch (FacebookException ex) {
                        Logger.getLogger(PublicacionesFacebook.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Elija cuantos post", null, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Elija un usuario", null, JOptionPane.INFORMATION_MESSAGE);
        }

    }                                        

    private void jButtonVerPostActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        jLabelImage.getGraphics().clearRect(1, 1, jLabelImage.getWidth(), jLabelImage.getHeight());
        jTextAreaComments.setText("");
        try {
            mostrarPost();
        } catch (IOException ex) {
            Logger.getLogger(PublicacionesFacebook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                              

    private void jTextNameUserActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jTextGenderActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublicacionesFacebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublicacionesFacebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublicacionesFacebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublicacionesFacebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublicacionesFacebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonVerPost;
    private javax.swing.JComboBox jComboPostNumber;
    private javax.swing.JComboBox jComboUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablePost;
    private javax.swing.JTextArea jTextAreaComments;
    private javax.swing.JTextArea jTextAreaPost;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldLikesNumber;
    private javax.swing.JTextField jTextFieldQuienPublica;
    private javax.swing.JTextField jTextGender;
    private javax.swing.JTextField jTextNameUser;
    // End of variables declaration                   
}
